### PR TITLE
Project: NewYork Times Page

### PR DESCRIPTION
**Pull request by taiwocoker**
## In this milestone, we:
- Added the Navigation bar
- Added the Subscribe and Sign-in button
- Added the Articles
- Added the Footer

### CODE REVIEW

**Review by christianotieno — COMMENTED** [review]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @taiwocoker & @Abdoulaye-Thespy   :wave:
-
Good job with this project.  The general layout looks good. 

We, however, do have some few changes to carry out before we proceed (see review comment).
##

## [REQUIRED] - IMPLEMENT - The theory of inflation
While I was conducting the review, I noticed that you guys did not implement this section as it was required of you.
- This is usually the trickiest of parts with this project and it is where we learn the most implementing it with some grid and flex tricks. 😉 

I expected to see maybe, a background image of the icons with wordings floated to their exact places as is seen in the original.

Instead, this is what I was met with: 👇 
theory_of_inflation

An image copy of it embedded in our markup.
 
- I would kindly request for this section to be implemented. You are bound to learn so much from it.

## [REQUIRED] - FIX - Validation errors in the markup
You are [required](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) to run your markup document through a validator and remove the errors such as these: 👇 
validator

Please use this [validator](https://validator.w3.org/#validate_by_input) for the same. 

## [REQUIRED] - FIX - These sections

- The styling appears a bit off in these sections: 
1. Change this:👇 
section_clone

Let's employ our prowess and make it match this: 👇 
section_original

2.  From this: 👇

editors_pick_clone

Fix the line to resemble this: 👇 

editors_pick
 
## [REQUIRED] - FIX - The footer section
From this: 👇 

footer_clone

To resemble this: 👇 

footer_original

## [REQUIRED] - FIX - Use of images.
When embedding images in our markup the caption should never be part of the pic.
Like in this case: 👇 

caption_img_1


- Kindly separate the two and implement them independently. Thank you.

## [REQUIRED] - ADD - Responsive support to smaller screens.
Your page seems not to be responsive in smaller screens, something you might have bypassed, unfortunately. 
- Kindly apply your amazing skills to this and let's make our site responsive, shall we? 😄 Awesome 💪 

Please makes changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be happy to assist. You can also reach me and connect with me on my social media or email. :eyes:

##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  TEAM👏👏👏

**Great job here @taiwocoker and @Abdoulaye-Thespy** 🎉🎉
This project meets the requirements for approval.


**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
